### ISSUE TITLE
Could not obtain battery state.

### ISSUE THREAD

**Issue by JohanLindahl72** [g-mocken/ZoeStatus#10]
Hi,

The app worked in the beginning showing how much battery was left and so on.

Now it shows an error "Could not obtain battery state." when started. I can still turn on the AC if I want.

Anyone have any clue?

Regards,

Johan Lindahl
![Zoe Status Error](https://user-images.githubusercontent.com/103940020/163811028-53227855-aaae-47f9-b43c-449e885b5383.jpeg)

**Comment by g-mocken** [comment]
This is a very generic kind of communication error. Whenever it occurs, please always check with the original "My Renault" app whether it can fetch the state. If not, then it is very likely a (temporary) backend-related error, which happens rather frequently, but typically goes away within a couple of hours.
If it persists and the Renault app continues to work, let me know.
