### ISSUE TITLE
ZoeStatus new user. 

### ISSUE THREAD

**Issue by 013Harkey** [g-mocken/ZoeStatus#11]
I'm having problems starting ZoeStatus, I've entered my email (username) and password in the settings but I still can't start the app. 

![B488D35C-BB02-4672-8976-BFA62527B850](https://user-images.githubusercontent.com/112932600/188577319-cd411e5c-d007-417f-aaa0-59cc4a0fd854.png)

**Comment by cathrinevaage** [comment]
Go into the settings app and change the «Kamereon key» field to `VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss`

**Comment by g-mocken** [comment]
See this thread for updated keys: https://github.com/g-mocken/ZoeStatus/issues/9
