### ISSUE TITLE
Start A/C on watch

### ISSUE THREAD

**Issue by steeeeeeeeevo** [g-mocken/ZoeStatus#2]
Hello

Is there any chance you can add Start A/C to the 3D Touch options on Apple Watch so it can be next to the refresh and request credentials options?

Thanks for the excellent app

Steve

**Comment by g-mocken** [comment]
Yes, in fact this feature has been present in the GitHub Repo for quite a while now (if you know how to compile and install it yourself). I simply have not found the time to create a new AppStore release with new screenshots for all kinds of devices and all the other requirements.

**Comment by steeeeeeeeevo** [comment]
Okay thanks. 
Unfortunately I have no idea how to do that.
Also I have found in the iOS 14 accessibility options there is a double and triple tap feature on the back of the phone with assignable shortcuts and quick launch tasks. 
Do you think it might be possible to assign launch A/C to this new feature at all? 

Steve

**Comment by g-mocken** [comment]
I have not investigated iOS 14, yet, so I cannot comment.
