### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by coolio2004** [g-mocken/ZoeStatus#3]
Hallo, seit dem letzten IOS update bekomme ich keine Verbindung mehr zu meiner Zoe. My Renault und Zeddy funktionieren. Falls du Betas mit Testflight anbieten solltest, wäre ich gerne dabei. Ich danke dir für deine Mühen. Hans@coolio2004

**Comment by g-mocken** [comment]
Hier ist ein Versuch, der aber bei anderen noch nicht den gewünschten Erfolg brachte:
https://testflight.apple.com/join/lT0KBqzh
Ich tappe leider noch im Dunkeln, woran es genau liegt (denn bei meiner Q210 geht alles).

**Comment by coolio2004** [comment]
Hallo Guido,
leider geht die Testflight bei mir nicht - immer noch login failed. Es ist so schade, da ich den Status auf meiner Applewatch bisher anzeigen lassen konnte. Endlich geht nach 3 Monaten bei mir jetzt die Vorklimatisierung im Rahmen der Renault Rückruf Aktion. Wäre zu schön, wenn man jetzt auch die Vorklimatisierung auf der watch starten könnte.
Ich teste gerne für dich weiter.
LG
Hans

Von meinem iPad Pro gesendet

**Comment by g-mocken** [comment]
Ich habe eine neue Version hochgeladen, die zwar nichts verbessert, aber aussagekräftigere Fehlermeldungen liefert. Bitte Screenshot via TestFlight-Feedback einsenden!

**Comment by coolio2004** [comment]
Hallo- leider geht auch die neue nicht




Von meinem iPhone gesendet

**Comment by g-mocken** [comment]
Die Fehlermeldung sollte sich aber geändert (erweitert!) haben - ich brauche den genauen Text, am besten einen Screenshot machen. Dazu in TestFlight "Beta-Feedback senden" wählen, "Bildschirmfoto hinzufügen" und dann Screenshot auswählen, den man zuvor gemacht hat.

**Comment by coolio2004** [comment]
Habe ich gerade gemacht

Von meinem iPad Pro gesendet

**Comment by g-mocken** [comment]
Danke, hab' jetzt was korrigiert und eine neue Version hochgeladen ins TestFlight. Bitte Bescheid geben, wenn's geholfen hat.

**Comment by g-mocken** [comment]
Wenn ich Deinen neuen Screenshot richtig deute: Login geht jetzt, km-Stand wird richtig angezeigt, aber Ladestand noch nicht. Wenn das reproduzierbar ist (kann immer mal zufällig seitens Renault für kurze Zeit hängen), dann
probier mal in den Settings "API for remote access" beide Möglichkeiten v1/v2 aus.

**Comment by coolio2004** [comment]
Guten Morgen Guido,
mit V2 geht es wieder. SoC wird auch angezeigt. Kannst du auf der Watch noch einen Button für adhoc Klimatisierung einrichten? Dann wäre alles perfekt.
LG
Hans

Von meinem iPad Pro gesendet

**Comment by g-mocken** [comment]
Fein, V2 mache ich jetzt auch zum Standard. 
A/C Trigger auf der Watch gibt's doch schon!

**Comment by coolio2004** [comment]
Hallo Guido,
ich hatte den a/c Button übersehen -soft touch. Leider funktioniert er nicht immer -genau so bei der Renault App. Komischerweise löst Zeddy die Befehle eigentlich auf Anhieb aus.
Vielen Dank, dass du die App wieder ans Laufen gebracht hast. Falls es wieder was zu Testen gibt, mach ich das gerne für dich. Als Rentner  habe ich viel Zeit.
LG aus dem Rheinland.
Hans

Von meinem iPad Pro gesendet

**Comment by g-mocken** [comment]
Ich glaube, es ist Zufall, dass es bei Dir mit Zeddy öfter geklappt hat. Es steckt bei allen Apps überall dieselbe Schnittstelle dahinter. Manchmal spinnt das Backend bei Renault, manchmal steht die ZOE im Funkloch oder ist tief "eingeschlafen" ... es ist leider einfach unzuverlässig.
