### ISSUE TITLE
App doesn't work anymore - Kamereon error

### ISSUE THREAD

**Issue by TeutoRockA** [g-mocken/ZoeStatus#4]
App doesn't work anymore  - possible change of ZOE Api, Kamereon error occurs
![IMG_586D46C161C8-1](https://user-images.githubusercontent.com/78411376/106577966-4af75400-653f-11eb-8b51-52cfb513d5b3.jpeg)

Due to goingElectric Forum ([https://www.goingelectric.de/forum/viewtopic.php?f=57&t=64598](url)) a new key is needed:

kamareonAPI = "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2"

**Comment by chfleischmann** [comment]
Muss der neue api Schlüssel in der App vom Programmierer hinterlegt werden oder müssen wir den api als Endkunde irgendwo eingeben?

**Comment by g-mocken** [comment]
I am currently implementing a new setting where this key can be entered by the user. 
The key could be preconfigured as default, but this could create legal issues.
I still hope someone figures out a way to retrieve this new key from a server, like it used to work in the past.

**Comment by chfleischmann** [comment]
Brauchst du den neuen Key?

"Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2"

Aber ich glaube den Key haben wir schon ein paar aus unserem Forum gegeben?

Mit freundlichen Grüßen

Christian Fleischmann
Am Unkenteich 26c
68259 Mannheim
Tel 06217992358
Fax 06217992841
Mail christianfleischmann@gmx.de

**Comment by g-mocken** [comment]
A preview of the fix (including the above key) will soon be available here https://testflight.apple.com/join/lT0KBqzh. It is currently still in app review.

**Comment by chfleischmann** [comment]
Thank you, but if I try this link I get a message back that you are no more betatester accepting :-(

Please could you accept me as betagtester ?
My Apple iDisk my E-Mail Adress..

Thank you:-)



Mit freundlichen Grüßen

Christian Fleischmann
Am Unkenteich 26c
68259 Mannheim 
Germany
Tel 06217992358
christianfleischmann@gmx.de

> Am 03.02.2021 um 14:59 schrieb Guido Mocken <notifications@github.com>:
> 
> lT0KBqzh

**Comment by g-mocken** [comment]
Ignore the misleading error message - the link will work _**after app review by Apple is complete**_.

**Comment by g-mocken** [comment]
Testflight is now active. Does it work for everybody? (Testflight sollte jetzt gehen - klappt's bei Euch?)

**Comment by chfleischmann** [comment]
Yes, I downloaded it yesterday and is working perfectly.

Superb idea that you can change the api key for yourself.

Thank you

Mit freundlichen Grüßen

Christian Fleischmann

Mail christianfleischmann@gmx.de

**Comment by TeutoRockA** [comment]
Works perfectly!!! Thanks 🤩 

Klappt prima, danke!!!

**Comment by g-mocken** [comment]
Updated version is in AppStore.
