### ISSUE TITLE
Not working on my iPad P

### ISSUE THREAD

**Issue by jadean** [g-mocken/ZoeStatus#5]
The app is not working with my iPad Pro or my iPhone 12 Pro

**Comment by g-mocken** [comment]
Can you provide more details?
Do you have a MY Renault account for you ZOE and is the original MY Renault app working for you (on those devices)?

**Comment by jadean** [comment]
Yes a have got a my Renault account and it is working on both devices 
When I go into ZoeStatus it opens up then shuts down almost straight a way

**Comment by g-mocken** [comment]
So it basically crashes before anything else happens? I guess you already tried a clean install?
Can you try the last TestFlight version https://testflight.apple.com/join/lT0KBqzh and, if necessary, allow it to provide a crash report?
