### ISSUE TITLE
Current Position

### ISSUE THREAD

**Issue by chrislp** [g-mocken/ZoeStatus#8]
Is it possible to get the car's current position? The _My Renault_ app shows me _my_ current position which is useless if I don't remember where I parked my car.

**Comment by chrislp** [comment]
I think I just answered my own question:

> /location (GET): The server returns 501 Not Implemented.

😔

**Comment by g-mocken** [comment]
You may want to check out https://github.com/jamesremuscat/pyze/issues/45.
(Apparently, it only works for ZE50 cars.)
